import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>0xFable</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="font-serif text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            <span className="font-mono font-light text-red-400">0x</span>FABLE
          </h1>
          <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 md:gap-8">
            <Link
              className="flex max-w-xs flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20"
              href="/play"
              target="_blank"
            >
              <h3 className="text-2xl font-bold">Play →</h3>
              {/* <div className="text-lg">
                Just the basics - Everything you need to know to set up your
                database and authentication.
              </div> */}
            </Link>
            <Link
              className="flex max-w-xs flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20"
              href="/learn"
              target="_blank"
            >
              <h3 className="text-2xl font-bold">Learn →</h3>
              {/* <div className="text-lg">Learn how to play 0xFable.</div> */}
            </Link>
          </div>
          {/* <Web3Button />; */}
        </div>
      </main>
    </>
  );
};

export default Home;
