import { useWeb3Modal, Web3Button } from "@web3modal/react"
import { type NextPage } from "next"
import Head from "next/head"
import { useAccount } from "wagmi"
import { CreateGameModal } from "../components/modals/createGameModal"
import { JoinGameModal } from "../components/modals/joinGameModal"
import { MintGameModal } from "../components/modals/mintDeckModal"
import Link from "next/link"
import dynamic from "next/dynamic"

const Home: NextPage = () => {
  const { address } = useAccount()
  const { open } = useWeb3Modal()

  return (
    <>
      <Head>
        <title>0xFable</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="font-serif text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            <span className="font-mono font-light text-red-400">0x</span>FABLE
          </h1>

          {address && (
            <div className="grid grid-cols-1 gap-4 sm:grid-cols-4 md:gap-8">
              <CreateGameModal />
              <JoinGameModal />
              <MintGameModal />
              <Link className="hover:border-3 btn-lg btn border-2 border-green-900 text-2xl normal-case hover:scale-105 hover:border-green-800" href={"/collection"}>
                Collection →
              </Link>
            </div>
          )}

          {!address && (
            <div className="">
              <button
                className="btn-lg btn border-2 border-yellow-500 normal-case hover:scale-105 hover:border-yellow-400"
                onClick={async () => {
                  await open();
                }}
              >
                Connect Wallet
              </button>
            </div>
          )}

          {/* TODO: Theme the button */}
          {address && <Web3Button /> }
        </div>
      </main>
    </>
  )
}

export default dynamic(() => Promise.resolve(Home), {
  ssr: false,
})