name: Check project

on:
  push:
    branches: [master]
  pull_request:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v3
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
      - name: Fake contract deploymment
        run: mkdir -p packages/contracts/out && echo "{}" > packages/contracts/out/deployment.json
      - run: make setup
      - run: make check

